---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hello
        image: image-name-placeholder
        ports:
        - containerPort: 1970
        livenessProbe:
          httpGet:
            path: /health
            port: 1970
