apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: de.icr.io/nl82485/demo/hello:ef2f2c2469c5819c3645367245fb8441da308926
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
