apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:3f6e1ade80feb91148667b36106021f48cf3867e
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
