apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: image-name-placeholder
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:9e6cea0b66ae1c05c80cfaa829b3944f2ce468d7
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
