apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: image-name-placeholder
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:2a9fe4bee8e74833526f406a5838e0c10c64ada9
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
