apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:3a9aaa3f9d22efa24832c18b64f1a16fb9a7da76
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
