apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: image-registry.openshift-image-registry.svc:5000/showme/hello:42052813a2be313fdab89b0eb14e132f8e55b37a
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
