apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:a8ede44616660f991d5c3cdf43f99ba2252be6cc
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
