apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: image-name-placeholder
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:ed034140a7f93684bebba1e40500e396ad5e1cef
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
