apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: image-name-placeholder
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:c761a573bd0cdeef1ab296dad8c7a23ffe211f1f
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
