apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:12fbc852a0ade9dfa56923a33ec57173b965424b
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
