apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: image-name-placeholder
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:752e0d6b06e7e5a929842aebbc5e0bcc4710b361
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
