apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:d548dffa06ee7d6a2fdf4d9aca38f2b01417f6d2
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
