apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: hello
images:
- name: hello-image
  newName: image-registry.openshift-image-registry.svc:5000/demo/hello:5debf918615e89be2357c75aa832dd7676fc71aa
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
