---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hello
images:
  - name: hello-image
    newName: image-registry.openshift-image-registry.svc:5000/showme/hello:1.0
resources:
- deployment.yaml
- service.yaml
